version: "3"

includes:
  kind:
    taskfile: ./kind
    dir: ./kind

  nginx-ingress-controller:
    taskfile: ./nginx-ingress-controller
    dir: ./nginx-ingress-controller

  grafana:
    taskfile: ./grafana
    dir: ./grafana