version: "3"

includes:
  # ================================
  #   ENVIRONMENTS
  # --------------------------------
  environments:
    taskfile: ./environments/taskfile.yaml

  # ================================
  #   BRICKS
  # --------------------------------
  cert-manager:
    taskfile: ./bricks/cert-manager
    dir: ./bricks/cert-manager

  cilium:
    taskfile: ./bricks/cilium
    dir: ./bricks/cilium

  grafana:
    taskfile: ./bricks/grafana
    dir: ./bricks/grafana

  kind:
    taskfile: ./bricks/kind
    dir: ./bricks/kind

  kyverno:
    taskfile: ./bricks/kyverno
    dir: ./bricks/kyverno

  nginx-ingress-controller:
    taskfile: ./bricks/nginx-ingress-controller
    dir: ./bricks/nginx-ingress-controller

  prometheus-stack:
    taskfile: ./bricks/prometheus-stack
    dir: ./bricks/prometheus-stack

  tekton:
    taskfile: ./bricks/tekton
    dir: ./bricks/tekton

  # ================================
  #   INTERNALS
  # --------------------------------
  helpers:
    taskfile: ./helpers
    internal: true

tasks:
  cleanup:
    cmds:
      - task: kind:delete

  create-self-signed-ca-certificate:
    cmds:
      - test -d certificates || mkdir certificates
      - >-
        openssl req -x509 -newkey rsa:4096 -keyout certificates/sandbox.local.key -out certificates/sandbox.local.crt 
        -sha256 -days 3650 -nodes -subj "/CN=sandbox.local" 
        -addext "subjectAltName=DNS:sandbox.local,DNS:*.sandbox.local,IP:127.0.0.1"
      - echo "Add certificates/sandbox.local.crt to your browser"

    status:
      - test -f certificates/sandbox.local.key
      - test -f certificates/sandbox.local.crt