version: "3"
dotenv:
  - .env
  - "{{ .ENV }}/.env"
  - "{{ .HOME }}/.env"
includes:
  manage:
    taskfile: ./tasks/manage.taskfile.yaml
  helm:
    taskfile: ./tasks/helm.taskfile.yaml
  env:base:
    taskfile: ./environments/base/taskfile.yaml
    dir: ./environments/base
  brick:kind:
    taskfile: ./bricks/kind/taskfile.yaml
    dir: ./bricks/kind
  brick:cert-manager:
    taskfile: ./bricks/cert-manager/taskfile.yaml
    dir: ./bricks/cert-manager
