version: "3"

includes:
  kind:
    taskfile: ./kind
    dir: ./kind

  cert-manager:
    taskfile: ./cert-manager
    dir: ./cert-manager

  nginx-ingress-controller:
    taskfile: ./nginx-ingress-controller
    dir: ./nginx-ingress-controller

  grafana:
    taskfile: ./grafana
    dir: ./grafana