version: '3'
dotenv:
  - .env
  - '{{ .ENV }}/.env'
  - '{{ .HOME }}/.env'
includes:
  init:
    taskfile: ./tasks/init.taskfile.yaml
  todo:
    taskfile: ./tasks/todo.taskfile.yaml
  hosts:
    taskfile: ./tasks/hosts.taskfile.yaml
  manage:
    taskfile: ./tasks/manage.taskfile.yaml
  helm:
    taskfile: ./tasks/helm.taskfile.yaml
  env:base:
    taskfile: ./environments/base/taskfile.yaml
    dir: ./environments/base
  brick:cert-manager:
    taskfile: ./bricks/cert-manager/taskfile.yaml
    dir: ./bricks/cert-manager
  brick:k3d:
    taskfile: ./bricks/k3d/taskfile.yaml
    dir: ./bricks/k3d
  brick:prometheus-stack:
    taskfile: ./bricks/prometheus-stack/taskfile.yaml
    dir: ./bricks/prometheus-stack
  brick:grafana:
    taskfile: ./bricks/grafana/taskfile.yaml
    dir: ./bricks/grafana
  brick:nginx-ingress-controller:
    taskfile: ./bricks/nginx-ingress-controller/taskfile.yaml
    dir: ./bricks/nginx-ingress-controller
