version: "3"

includes:
  # ================================
  #   USER FACING
  # --------------------------------
  kind:
    taskfile: ./bricks/kind
    dir: ./bricks/kind

  cert-manager:
    taskfile: ./bricks/cert-manager
    dir: ./bricks/cert-manager

  nginx-ingress-controller:
    taskfile: ./bricks/nginx-ingress-controller
    dir: ./bricks/nginx-ingress-controller

  prometheus-stack:
    taskfile: ./bricks/prometheus-stack
    dir: ./bricks/prometheus-stack

  grafana:
    taskfile: ./bricks/grafana
    dir: ./bricks/grafana

  # ================================
  #   INTERNALS
  # --------------------------------
  helpers:
    taskfile: ./helpers
    internal: true

tasks:
  cleanup:
    cmds:
      - task: kind:delete