version: "3"

tasks:
  deploy:
    preconditions: []
    status: []
    cmds:
      - task: :manage:check-installation
      - task: :brick:kind:install
      - task: :brick:cert-manager:install
#      - task: :brick:nginx-ingress-controller:install
#      - task: :brick:prometheus-stack:install

  tear-down:
    preconditions: []
    status: []
    cmds:
      - task: :manage:check-installation
      - task: :brick:kind:remove

  redeploy:
    preconditions: []
    status: []
    cmds:
      - task: :manage:check-installation
      - task: tear-down
      - task: deploy

  # E2E test
#  test-e2e:
#    cmds:
#      - task: test-before-all
#      - task: test-1
#      - task: ...
#      - task: test-after-all

  # Create test resources and setup
#  test-before-all:
#    internal: true

  # Tear down test resources and setup
#  test-after-all:
#    internal: true

  # A test
#  test-1:
#    internal: true
#    interactive: true