version: "3"

tasks:
  deploy:
    desc: Create a new base environment
    preconditions: []
    status: []
    cmds:
      - task: :init:check-installation
      - task: :brick:k3d:cluster:create
      - task: :brick:cert-manager:deploy
  #      - task: :brick:nginx-ingress-controller:install
  #      - task: :brick:prometheus-stack:install

  tear-down:
    desc: Delete the environment
    preconditions: []
    status: []
    cmds:
      - task: :brick:k3d:cluster:delete

  redeploy:
    desc: Delete then recreate the environment
    preconditions: []
    status: []
    cmds:
      - task: tear-down
      - task: deploy
