# https://cert-manager.io/docs/configuration/ca/
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer-sandbox-local
  labels:
    sandbox/issuer: "ca"
spec:
  ca:
    secretName: ca-root
