version: "3"

tasks:
  obj:new:
    internal: true
    preconditions:
      - sh: |
          [[ "{{ .NAME }}" =~ ^[a-z][a-z0-9\-]+[a-z0-9]$ ]]
        msg: >-
          Invalid NAME provided: "{{ .NAME }}".
          Must match ^[a-z][a-z0-9\-]+[a-z0-9]$

    status:
      - test -d ./{{ .KIND_PLURAL }}/{{ .NAME }}

    cmds:
      - mkdir -p ./{{ .KIND_PLURAL }}/{{ .NAME }}
      - cp -r ./templates/{{ .KIND_SINGULAR }}/* ./{{ .KIND_PLURAL }}/{{ .NAME }}/
      - yq -y -i '.includes += {"{{ .KIND_KEY }}:{{ .NAME }}":{"taskfile":"./{{ .KIND_PLURAL }}/{{.NAME}}/taskfile.yaml","dir":"./{{ .KIND_PLURAL }}/{{.NAME}}"}}' taskfile.yaml

  obj:delete:
    internal: true
    prompt: You're about to delete one {{ .KIND_SINGULAR }} (folder and associated tasks)... Do you wish to continue?
    preconditions:
      - sh: |
          [[ "{{ .NAME }}" =~ ^[a-z][a-z0-9\-]+[a-z0-9]$ ]]
        msg: >-
          Invalid NAME provided: "{{ .NAME }}".
          Must match ^[a-z][a-z0-9\-]+[a-z0-9]$

    status:
      - test ! -d ./{{ .KIND_PLURAL }}/{{ .NAME }}

    cmds:
      - rm -rf ./{{ .KIND_PLURAL }}/{{ .NAME }}/
      - yq -yi 'del(.includes["{{ .KIND_KEY }}:{{ .NAME }}"])' taskfile.yaml

  brick:new:
    desc: Create a brick folder and associated tasks.
    summary: |
      Create a brick folder and associated tasks. Name must be specify in an environment variable:
      NAME=my-brick task manage:brick:new
    cmds:
      - task: obj:new
        vars:
          KIND_PLURAL: bricks
          KIND_SINGULAR: brick
          KIND_KEY: brick

  brick:delete:
    desc: Delete the brick folder and associated tasks.
    summary: |
      Delete the brick folder and associated tasks. Name must be specify in an environment variable:
      NAME=my-brick task manage:brick:delete
    cmds:
      - task: obj:delete
        vars:
          KIND_PLURAL: bricks
          KIND_SINGULAR: brick
          KIND_KEY: brick

  env:new:
    desc: Create an environment folder and associated tasks.
    summary: |
      Create an environment folder and associated tasks. Name must be specify in an environment variable:
      NAME=my-env task manage:env:new
    cmds:
      - task: obj:new
        vars:
          KIND_PLURAL: environments
          KIND_SINGULAR: environment
          KIND_KEY: env

  env:delete:
    desc: Delete the environment folder and associated tasks.
    summary: |
      Delete the environment folder and associated tasks. Name must be specify in an environment variable:
      NAME=my-env task manage:env:delete
    cmds:
      - task: obj:delete
        vars:
          KIND_PLURAL: environments
          KIND_SINGULAR: environment
          KIND_KEY: env
