version: "3"

tasks:
  init:
    desc: Initialize a TODO.md file
    requires:
      vars:
        - EXK_ROOT_DIR
    cmds:
      - rm {{ .EXK_ROOT_DIR }}/TODO.md || true
      - touch {{ .EXK_ROOT_DIR }}/TODO.md

  add:
    desc: Add a TODO to the TODO.md file
    requires:
      vars:
        - EXK_TODO_CONTENT
        - EXK_ROOT_DIR
    status:
      - grep -q "{{ .EXK_TODO_CONTENT }}$" {{ .EXK_ROOT_DIR }}/TODO.md
    cmd: echo "- [ ] {{ .EXK_TODO_CONTENT }}" >> {{ .EXK_ROOT_DIR }}/TODO.md

  remove:
    desc: Remove a TODO to the TODO.md file
    requires:
      vars:
        - EXK_TODO_CONTENT
        - EXK_ROOT_DIR
    status:
      - test ! $(grep -q "{{ .EXK_TODO_CONTENT }}$" {{ .EXK_ROOT_DIR }}/TODO.md)
    cmd: grep -v "- [ ] {{ .EXK_TODO_CONTENT }}" {{ .EXK_ROOT_DIR }}/TODO.md > {{ .EXK_ROOT_DIR }}/TODO.md
