version: "3"

tasks:
  deploy:
    desc: "" # TODO
    preconditions: [] # TODO
    status: [] # TODO
    vars:
      EXK_PWD: $(pwd)
    cmds:
      - task: :helm:repo:add
        vars:
          EXK_REPO_NAME: gitlab
          EXK_REPO_URL: https://charts.gitlab.io/
      - task: :helm:repo:update
        vars:
          EXK_REPO_NAME: gitlab
      - task: :brick:k3d:namespace:create
        vars:
          EXK_NAMESPACE: scm
      - task: :helm:install
        vars:
          EXK_CHART: gitlab/gitlab
          EXK_RELEASE_NAME: gitlab
          EXK_NAMESPACE: scm
          EXK_WAIT: "true"
          EXK_EXTRA: >-
            -f bricks/gitlab/assets/values.yaml
            --set global.hosts.domain={{ .EXK_DOMAIN }}
            --set global.gitlab.name=gitlab.{{ .EXK_DOMAIN }}
            --set global.registry.name=gitlab-registry.{{ .EXK_DOMAIN }}
            --set global.minio.name=gitlab-minio.{{ .EXK_DOMAIN }}
            --timeout 600s
      - task: :hosts:add
        vars:
          EXK_HOSTNAME: gitlab.{{ .EXK_DOMAIN }}

  remove:
    desc: "" # TODO
    preconditions: [] # TODO
    status: [] # TODO
    cmds:
      - task: :hosts:remove
        vars:
          EXK_HOSTNAME: gitlab.{{ .EXK_DOMAIN }}
      - task: :helm:uninstall
        vars:
          EXK_RELEASE_NAME: gitlab
          EXK_NAMESPACE: scm

  redeploy:
    desc: "Removes the brick then redeploys it."
    cmds:
      - task: remove
      - task: deploy
