version: "3"

vars:
  KIND_CLUSTER_NAME: '{{ .KIND_CLUSTER_NAME | default "sandbox" }}'
  KIND_CLUSTER_CONFIG: '{{ .KIND_CLUSTER_CONFIG | default "test" }}'

tasks:
  delete:
    cmds:
      - kind delete cluster --name "{{ .KIND_CLUSTER_NAME }}"

  create:
    cmds:
      - kind create cluster --name "{{ .KIND_CLUSTER_NAME }}" --config "configs/{{ .KIND_CLUSTER_CONFIG }}.yaml"

  recreate:
    cmds:
      - task: delete
        ignore_error: true
        vars:
          KIND_CLUSTER_NAME: '{{ .KIND_CLUSTER_NAME | default "sandbox" }}'
          KIND_CLUSTER_CONFIG: '{{ .KIND_CLUSTER_CONFIG | default "simplest" }}'

      - task: create
        vars:
          KIND_CLUSTER_NAME: '{{ .KIND_CLUSTER_NAME | default "sandbox" }}'
          KIND_CLUSTER_CONFIG: '{{ .KIND_CLUSTER_CONFIG | default "simplest" }}'