version: "3"

tasks:
  deploy:
    desc: "" # TODO
    preconditions: [] # TODO
    status: [] # TODO
    cmds: [] # TODO

  remove:
    desc: "" # TODO
    preconditions: [] # TODO
    status: [] # TODO
    cmds: [] # TODO

  redeploy:
    desc: "Removes the brick then redeploys it."
    cmds:
      - task: remove
      - task: deploy
