version: "3"

tasks:
  deploy:
    desc: "Deploys the Prometheus stack" # TODO
    preconditions: [] # TODO
    status:
      - test $(kubectl get --namespace monitoring pod --no-headers  2> /dev/null | wc -l) -gt 0
    cmds:
      - task: :helm:repo:add
        vars:
          REPO_NAME: prometheus-community
          REPO_URL: https://prometheus-community.github.io/helm-charts
      - task: :helm:install
        vars:
          CHART_NAME: kube-prometheus-stack
          REPO_NAME: prometheus-community
          RELEASE_NAME: prometheus-stack
          NAMESPACE: monitoring
          CREATE_NAMESPACE: true
          CHART_VERSION: v69.4.1
          WAIT: "true"

  remove:
    desc: "Removes the Prometheus stack" # TODO
    preconditions: [] # TODO
    status:
      - test $(kubectl get --namespace monitoring pod --no-headers 2> /dev/null | wc -l) = 0
    cmds:
      - task: :helm:uninstall
        vars:
          RELEASE_NAME: prometheus-stack
          NAMESPACE: monitoring

  redeploy:
    desc: "Removes the brick then redeploys it."
    cmds:
      - task: remove
      - task: deploy
