version: "3"

tasks:
  deploy:
    preconditions: []
    status: []
    cmds: []

  tear-down:
    preconditions: []
    status: []
    cmds: []

  redeploy:
    preconditions: []
    status: []
    cmds:
      - task: :manage:check-installation
      - task: tear-down
      - task: deploy
