version: "3"

tasks:
  deploy:
    preconditions: []
    status: []
    cmds:
      # Verifies that all the tools are installed
      - task: :manage:check-installation

  # E2E test
#  test-e2e:
#    cmds:
#      - task: test-before-all
#      - task: test-1
#      - task: ...
#      - task: test-after-all

  # Create test resources and setup
#  test-before-all:
#    internal: true

  # Tear down test resources and setup
#  test-after-all:
#    internal: true

  # A test
#  test-1:
#    internal: true
#    interactive: true