configs:
  params:
    server.insecure: true

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: ca-issuer-sandbox-local
    path: "/"
    extraTls:
      - secretName: argocd-tls

crds:
  install: true
