version: "3"

vars:
  KIND_CLUSTER_NAME: '{{ .KIND_CLUSTER_NAME | default "sandbox" }}'
  KIND_CLUSTER_CONFIG: '{{ .KIND_CLUSTER_CONFIG | default "c1w3-exposed" }}'

tasks:
  deploy-cluster:
    desc: Create a new Kind cluster.
    summary: |
      Create a new kind cluster.

      variables:
       - KIND_CLUSTER_NAME: Name of the cluster.
       - KIND_CLUSTER_CONFIG: File's' stem of the cluster configuration to use (c1w0, c1w3-exposed...) See assets/configs.
    preconditions:
      - &check_cluster_name
        sh: |
          [[ "{{ .KIND_CLUSTER_NAME }}" =~ ^[a-zA-Z][a-zA-Z0-9]+[a-zA-Z0-9]$ ]]
        msg: >-
          Invalid KIND_CLUSTER_NAME provided: "{{ .KIND_CLUSTER_NAME }}".
          Must match ^[a-zA-Z][a-zA-Z0-9]+[a-zA-Z0-9]$
      - sh: test -f ./assets/configs/{{ .KIND_CLUSTER_CONFIG }}.yaml
        msg: >-
          Config "{{ .KIND_CLUSTER_CONFIG }} not found.

    status:
      - kind get clusters 2> /dev/null | grep -qE "^{{ .KIND_CLUSTER_NAME }}$"

    cmds:
      - kind create cluster --name "{{ .KIND_CLUSTER_NAME }}" --config "./assets/configs/{{ .KIND_CLUSTER_CONFIG }}.yaml"
      - kubectl create namespace kube-support
      - kubectl create namespace kube-security

  delete-cluster:
    desc: Delete a kind cluster with everything in it.
    summary: |
      Delete a kind cluster.

      variables:
       - KIND_CLUSTER_NAME: Name of the cluster.

    preconditions:
      - *check_cluster_name

    status:
      - test ! $(kind get clusters | grep -E "^{{ .KIND_CLUSTER_NAME }}$" && true || false)

    cmds:
      - kind delete cluster --name "{{ .KIND_CLUSTER_NAME }}"
