version: "3"

vars:
  CERT_MANAGER_CHART_VERSION: 1.16.2

tasks:
  install:
    preconditions: [] # TODO
    status:
      
    cmds:
      - task: create-certificate

      # See https://cert-manager.io/docs/installation/helm/
      - task: :helm:add-repo
        vars:
          REPO_NAME: jetstack
          REPO_URL: https://charts.jetstack.io
      - helm repo update jetstack

      - >-
        helm install cert-manager jetstack/cert-manager --namespace kube-security 
        --version v{{ .CERT_MANAGER_CHART_VERSION }} --set crds.enabled=true --wait
      - >-
        kubectl create secret tls --namespace kube-security ca-sandbox-local 
        --key {{ .ROOT_DIR }}/certificates/ca.crt
        --cert {{ .ROOT_DIR }}/certificates/ca.key
      - kubectl apply --server-side --namespace kube-security -f ./assets/cluster-issuer.yaml

  remove:
    cmds:
      - helm uninstall --namespace kube-security cert-manager
      - kubectl delete secret --namespace kube-security ca-sandbox-local
      - kubectl delete --namespace kube-security -f ./assets/cluster-issuer.yaml

  create-certificate:
    status:
      - test -f {{ .ROOT_DIR }}/certificates/ca.crt
      - test -f {{ .ROOT_DIR }}/certificates/ca.key

    cmds:
      - test -d {{ .ROOT_DIR }}/certificates/ || mkdir -p {{ .ROOT_DIR }}/certificates/
      - >-
        openssl req -x509 -newkey rsa:4096
        -keyout {{ .ROOT_DIR }}/certificates/ca.key
        -out {{ .ROOT_DIR }}/certificates/ca.crt
        -sha256 -days 3650 -nodes -subj "/CN=sandbox.local"
        -addext "subjectAltName=DNS:sandbox.local,DNS:*.sandbox.local,IP:127.0.0.1"

      - task: :manage:add-todo
        vars:
          CONTENT: 'Add certificate "./certificates/ca.crt" to the browser.'
      - task: :manage:add-todo
        vars:
          CONTENT: 'Add certificate "./certificates/ca.crt" to the system.'

  # E2E test
#  test-e2e:
#    cmds:
#      - task: test-before-all
#      - task: test-1
#      - task: ...
#      - task: test-after-all

  # Create test resources and setup
#  test-before-all:
#    internal: true

  # Tear down test resources and setup
#  test-after-all:
#    internal: true

  # A test
#  test-1:
#    internal: true
#    interactive: true