version: "3"

vars:
  CERT_MANAGER_CHART_VERSION: v1.16.2

tasks:
  deploy:
    desc: "Deploy Cert-Manager." # TODO
    requires:
      vars:
        - CERT_MANAGER_CHART_VERSION

    preconditions: [] # TODO
    status: [] # TODO
    cmds:
      - task: :init:check-installation
      - task: generate-certificate

      # Manage repository
      - task: :helm:add-repo
        vars:
          REPO_NAME: jetstack
          REPO_URL: https://charts.jetstack.io
      - helm repo update jetstack

      # Install cert-manager
      # See https://cert-manager.io/docs/installation/helm/
      - task: :helm:install
        vars:
          CHART_NAME: jetstack/cert-manager
          CHART_VERSION: "{{ .CERT_MANAGER_CHART_VERSION }}"
          RELEASE_NAME: cert-manager
          NAMESPACE: kube-security
          EXTRA: --set crds.enabled=true
          WAIT: "true"

  remove:
    desc: "Remove Cert-Manager (does not delete created certificates)" # TODO
    preconditions: [] # TODO
    status: [] # TODO
    cmds:
      - task: :init:check-installation
      - task: :helm:uninstall
        vars:
          RELEASE_NAME: cert-manager
          NAMESPACE: kube-security
          WAIT: "true"

  redeploy:
    desc: "Removes the brick then redeploys it."
    cmds:
      - task: remove
      - task: deploy

  # -----------------------------------
  # SUBTASKS
  # -----------------------------------

  generate-certificate:
    internal: true
    requires:
      vars:
        - ROOT_DIR
        - DOMAIN

    status:
      - test -f {{ .ROOT_DIR }}/certificates/{{ .DOMAIN }}.crt
      - test -f {{ .ROOT_DIR }}/certificates/{{ .DOMAIN }}.key

    cmds:
      - test -d {{ .ROOT_DIR }}/certificates/ || mkdir -p {{ .ROOT_DIR }}/certificates/
      - >-
        openssl req -x509 -newkey rsa:4096
        -keyout {{ .ROOT_DIR }}/certificates/{{ .DOMAIN }}.key
        -out {{ .ROOT_DIR }}/certificates/{{ .DOMAIN }}.crt
        -sha256 -days 3650 -nodes -subj "/CN={{ .DOMAIN }}"
        -addext "subjectAltName=DNS:{{ .DOMAIN }},DNS:*.{{ .DOMAIN }},IP:127.0.0.1"

      - task: :todo:add
        vars:
          CONTENT: >-
            (Optional) Add certificate \`./certificates/{{ .DOMAIN }}.crt\` to your system.
      - task: :todo:add
        vars:
          CONTENT: >-
            (Optional) Add certificate \`./certificates/{{ .DOMAIN }}.crt\` to your browser.
