version: "3"

tasks:
  standalone:
    cmds:
      - task: :kind:recreate
        vars:
          KIND_CLUSTER_CONFIG: c1w3-exposed
      - task: :cert-manager:deploy
      - task: :nginx-ingress-controller:deploy
      - task: deploy

  deploy:
    cmds:
      - task: :helpers:check-helm
      - task: :helpers:check-kubectl

      # Task and Pipeline
      # https://artifacthub.io/packages/helm/tekton/tekton-pipeline
      - helm repo add cdf https://cdfoundation.github.io/tekton-helm-chart/
      - helm upgrade --install tekton cdf/tekton-pipeline -f

      # Triggers
      # https://tekton.dev/docs/installation/triggers/
      - kubectl apply --filename https://storage.googleapis.com/tekton-releases/triggers/latest/release.yaml
      - kubectl apply --filename https://storage.googleapis.com/tekton-releases/triggers/latest/interceptors.yaml

      # Dashboard
      # https://tekton.dev/docs/dashboard/install/
      - kubectl apply --filename https://storage.googleapis.com/tekton-releases/dashboard/latest/release.yaml
      - task: :helpers:hosts-file
        vars:
          HOSTNAME: "tekton.sandbox.local"

      - kubectl wait --namespace=tekton-pipelines --for-condition=ready pod --timeout=90s

  deploy-pipelines:
    cmds:
      - task: :helpers:check-helm



