version: "3"

tasks:
  deploy:
    desc: "" # TODO
    preconditions: [] # TODO
    status: [] # TODO
    cmds:
      - task: :helm:repo:add
        vars:
          EXK_REPO_NAME: nginx-stable
          EXK_REPO_URL: https://helm.nginx.com/stable
      - task: :helm:repo:update
        vars:
          EXK_REPO_NAME: nginx-stable
      - task: :brick:k3d:namespace:create
        vars:
          EXK_NAMESPACE: ingress
      - task: :helm:install
        vars:
          EXK_CHART: nginx-stable/nginx-ingress
          EXK_RELEASE_NAME: gnginx-ingress
          EXK_NAMESPACE: ingress
          EXK_WAIT: "true"

  remove:
    desc: "" # TODO
    preconditions: [] # TODO
    status: [] # TODO
    cmds:
      - task: :helm:uninstall
        vars:
          EXK_RELEASE_NAME: gnginx-ingress
          EXK_NAMESPACE: ingress

  redeploy:
    desc: "Removes the brick then redeploys it."
    cmds:
      - task: remove
      - task: deploy
