version: "3"

tasks:
  test01:
    cmds:
      - task: :kind:recreate
        vars:
          KIND_CLUSTER_CONFIG: c1w3-exposed-nocni
      - task: :cilium:deploy
      - task: :cert-manager:deploy
      - task: :nginx-ingress-controller:deploy # USE CILIUM INGRESS / GATEWAY
      - task: :prometheus-stack:deploy
      - task: :grafana:deploy