version: "3"

vars:
  CILIUM_CHART_VERSION: 1.16.4

tasks:
  standalone:
    cmds:
      - task: :kind:recreate
        vars:
          KIND_CLUSTER_CONFIG: c1w3-exposed-nocni
      - task: deploy
#      - task: test

  deploy:
    cmds:
      - task: :helpers:check-kubectl
      - task: :helpers:check-helm

      - helm repo add cilium https://helm.cilium.io/
      - |
        helm install cilium cilium/cilium --version {{ .CILIUM_CHART_VERSION }} \
          --namespace kube-system \
          --set image.pullPolicy=IfNotPresent \
          --set ipam.mode=kubernetes \
          --set hubble.relay.enabled=true \
          --set hubble.ui.enabled=true \
          --wait
      - kubectl apply --server-side -n kube-system -f manifests/ingress.yaml
      - task: :helpers:hosts-file
        vars:
          HOSTNAME: "hubble.sandbox.local"