version: "3"

tasks:
  deploy:
    preconditions: []
    status: []
    cmds:
      - task: :env:base:deploy
      - task: :brick:argocd:deploy

  tear-down:
    preconditions: []
    status: []
    cmds:
      - task: :env:base:tear-down

  redeploy:
    preconditions: []
    status: []
    cmds:
      - task: tear-down
      - task: deploy
