version: "3"

tasks:
  standalone:
    cmds:
      - task: :kind:recreate
        vars:
          KIND_CLUSTER_CONFIG: test
      - task: deploy
      - task: test

  deploy:
    cmds:
      # https://github.com/kyverno/kyverno/blob/release-1.13/charts/kyverno/values.yaml
      - helm repo add kyverno https://kyverno.github.io/kyverno/
      - helm repo update
      - helm install kyverno kyverno/kyverno -n kube-security --create-namespace -f values.yaml --wait

  test:
    cmds:
      # Namespace policy
      - kubectl apply --server-side -f tests/policy-label-required.yaml
      - kubectl run --image=busybox test-kyverno-policy-ko -- sleep 1h && exit 1 || echo "OK"
      - kubectl run --image=busybox test-kyverno-policy-ok --labels=sandbox.local/name=TEST -- sleep 1h

      # Clean the test
      - kubectl delete pod test-kyverno-policy-ok
      - kubectl delete -f tests/policy-label-required.yaml

      # ClusterPolicy
      - kubectl apply --server-side -f tests/clusterpolicy-label-required.yaml
      - kubectl run --image=busybox -n kube-support test-kyverno-policy-ko -- sleep 1h && exit 1 || echo "OK"
      - kubectl run --image=busybox -n kube-support test-kyverno-policy-ok --labels=sandbox.local/name=TEST -- sleep 1h

      # Clean the test
      - kubectl delete pod -n kube-support test-kyverno-policy-ok
      - kubectl delete -f tests/clusterpolicy-label-required.yaml
